"""add detections table

Revision ID: 1e6ea9d784c9
Revises: 3976409257c3
Create Date: 2026-07-12 08:36:12.721243
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e6ea9d784c9'
down_revision: Union[str, None] = '3976409257c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.Column('technique_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['threat_events.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_status'))
        batch_op.drop_index(batch_op.f('ix_detections_rule_id'))
        batch_op.drop_index(batch_op.f('ix_detections_org_id'))
        batch_op.drop_index(batch_op.f('ix_detections_device_id'))
        batch_op.drop_index(batch_op.f('ix_detections_created_at'))

    op.drop_table('detections')
    # ### end Alembic commands ###
