"""add integrations

Revision ID: 36c93274741b
Revises: 44af865f5376
Create Date: 2026-07-12 09:04:31.586308
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '36c93274741b'
down_revision: Union[str, None] = '44af865f5376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('min_severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_org_id'))

    op.drop_table('integrations')
    # ### end Alembic commands ###
