"""add organizations and org_id scoping

Revision ID: 3976409257c3
Revises: 967f09a44a35
Create Date: 2026-07-12 08:24:23.540318
"""
import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3976409257c3'
down_revision: Union[str, None] = '967f09a44a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Keep in sync with app.models.DEFAULT_ORG_ID.
DEFAULT_ORG_ID = "00000000000000000000000000000001"
_SCOPED_TABLES = ("devices", "threat_events", "quarantine_items",
                  "blocklist", "audit_log", "users")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_log_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_audit_log_org', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_blocklist_org_id'), ['org_id'], unique=False)
        batch_op.create_unique_constraint('uq_blocklist_org_value', ['org_id', 'value'])
        batch_op.create_foreign_key('fk_blocklist_org', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_devices_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_devices_org', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('quarantine_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_quarantine_items_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_quarantine_items_org', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('threat_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_threat_events_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_threat_events_org', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_users_org', 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###

    # -- data migration: create the default org and backfill existing rows ---
    organizations = sa.table(
        "organizations",
        sa.column("id", sa.String), sa.column("name", sa.String),
        sa.column("slug", sa.String), sa.column("is_active", sa.Boolean),
        sa.column("created_at", sa.DateTime),
    )
    op.bulk_insert(organizations, [{
        "id": DEFAULT_ORG_ID, "name": "Default Organization", "slug": "default",
        "is_active": True, "created_at": datetime.datetime.now(datetime.timezone.utc),
    }])
    for table in _SCOPED_TABLES:
        op.execute(
            sa.text(f"UPDATE {table} SET org_id = :oid WHERE org_id IS NULL")
            .bindparams(oid=DEFAULT_ORG_ID)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_org', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('threat_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_threat_events_org', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_threat_events_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('quarantine_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quarantine_items_org', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_quarantine_items_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_devices_org', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_devices_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blocklist_org', type_='foreignkey')
        batch_op.drop_constraint('uq_blocklist_org_value', type_='unique')
        batch_op.drop_index(batch_op.f('ix_blocklist_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_log_org', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_log_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
