"""add response_actions

Revision ID: 44af865f5376
Revises: cc6ab54ef5b3
Create Date: 2026-07-12 08:54:56.670269
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44af865f5376'
down_revision: Union[str, None] = 'cc6ab54ef5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_actions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_actions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_actions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_actions_status'))
        batch_op.drop_index(batch_op.f('ix_response_actions_org_id'))
        batch_op.drop_index(batch_op.f('ix_response_actions_device_id'))
        batch_op.drop_index(batch_op.f('ix_response_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_response_actions_action_type'))

    op.drop_table('response_actions')
    # ### end Alembic commands ###
