"""add device_groups policies and licensing

Revision ID: 94382bb5a702
Revises: 36c93274741b
Create Date: 2026-07-12 09:08:34.084044
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94382bb5a702'
down_revision: Union[str, None] = '36c93274741b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_group_org_name')
    )
    with op.batch_alter_table('device_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_groups_org_id'), ['org_id'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_devices_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key('fk_devices_group', 'device_groups', ['group_id'], ['id'])

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        # Server defaults so existing organization rows backfill cleanly.
        batch_op.add_column(sa.Column('license_tier', sa.String(length=32),
                                      nullable=False, server_default='community'))
        batch_op.add_column(sa.Column('max_devices', sa.Integer(),
                                      nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('max_devices')
        batch_op.drop_column('license_tier')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_devices_group', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_devices_group_id'))
        batch_op.drop_column('group_id')

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_org_id'))
        batch_op.drop_index(batch_op.f('ix_policies_group_id'))

    op.drop_table('policies')
    with op.batch_alter_table('device_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_groups_org_id'))

    op.drop_table('device_groups')
    # ### end Alembic commands ###
