"""add device_inventory

Revision ID: cc6ab54ef5b3
Revises: d54bd0f431a1
Create Date: 2026-07-12 08:51:17.083036
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc6ab54ef5b3'
down_revision: Union[str, None] = 'd54bd0f431a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_inventory',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('os_version', sa.String(length=255), nullable=False),
    sa.Column('kernel', sa.String(length=255), nullable=False),
    sa.Column('cpu_model', sa.String(length=255), nullable=False),
    sa.Column('cpu_count', sa.Integer(), nullable=False),
    sa.Column('ram_total_mb', sa.Integer(), nullable=False),
    sa.Column('disk_total_gb', sa.Integer(), nullable=False),
    sa.Column('disk_free_gb', sa.Integer(), nullable=False),
    sa.Column('installed_software', sa.JSON(), nullable=False),
    sa.Column('running_services', sa.JSON(), nullable=False),
    sa.Column('logged_in_users', sa.JSON(), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('posture', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    with op.batch_alter_table('device_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_inventory_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_inventory_org_id'))

    op.drop_table('device_inventory')
    # ### end Alembic commands ###
