"""add iocs and intel_rules

Revision ID: d54bd0f431a1
Revises: 1e6ea9d784c9
Create Date: 2026-07-12 08:47:27.084345
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd54bd0f431a1'
down_revision: Union[str, None] = '1e6ea9d784c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intel_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intel_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intel_rules_org_id'), ['org_id'], unique=False)

    op.create_table('iocs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('ioc_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'ioc_type', 'value', name='uq_ioc_org_type_value')
    )
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iocs_ioc_type'), ['ioc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_iocs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iocs_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iocs_value'))
        batch_op.drop_index(batch_op.f('ix_iocs_org_id'))
        batch_op.drop_index(batch_op.f('ix_iocs_ioc_type'))

    op.drop_table('iocs')
    with op.batch_alter_table('intel_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intel_rules_org_id'))

    op.drop_table('intel_rules')
    # ### end Alembic commands ###
